version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/apps/api"
      - "/apps/web"
      - "/apps/worker"
      - "/packages/client-sdk"
      - "/packages/config"
      - "/packages/database"
      - "/packages/domain"
      - "/packages/observability"
      - "/packages/ui"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      npm-deps:
        patterns: ["*"]
  - package-ecosystem: "github-actions"
    directories:
      - "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      github-actions-deps:
        patterns: ["*"]
